### ISSUE TITLE
gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

### ISSUE THREAD

**Issue by izzylaif** [ivan-hc/Anydesk-appimage#1]
На манжаре/раче крайний билд 6.1 выдает ошибку
`(anydesk:1545): GdkPixbuf-CRITICAL **:  gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed`
видимо надо патчить glib2 внутри appimage
предыдущие билды 5 работали

**Comment by ivan-hc** [comment]
Anyway, is the AppImage running/working as expected?

**Comment by ivan-hc** [comment]
I also get gtk errors, but the app works for me. If it is so for you too, you can safely ignore the errors.

**Comment by izzylaif** [comment]
> Anyway, is the AppImage running/working as expected?

Nope, not really. it just closes since it cannot set a window without even showing the interface. I tried the usual tinkering, i.e. change gtk theme in KDE and so on.

**Comment by ivan-hc** [comment]
uhm... you said that the version 5 worked well, it was based on Debian Stable, while this one is based on Debian Olstable.

I can try to rebuild this using Debian Stable again.

Let me know if the next release is ok for you, it will be ready from about 15 minutes from now.

EDIT: is available now https://github.com/ivan-hc/Anydesk-appimage/releases/download/continuous/Anydesk-6.2.1-1-x86_64.AppImage

**Comment by izzylaif** [comment]
The new one just hangs without showing any interface, until you kill it.
The one that works is 5.5.6. It still throws some errors, but works.

**Comment by ivan-hc** [comment]
I don't really know why this happens. You should check the AppRun into the AppImage:

    ./*.AppImage --appimage-extract
    cd squashfs-root/

the AppRun is just a shell script, you can test it by execute it:

    ./AppRun
remove `2> /dev/null` from the last line to see the outputs.

Let me know if you discover something.

**Comment by izzylaif** [comment]
It's the same error
`
squashfs-root  ./AppRun                                                                  127 ✘ 

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.754: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.755: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.755: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.755: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.755: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.755: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.755: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.755: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(anydesk:15170): GdkPixbuf-CRITICAL **: 23:27:40.755: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
terminate called after throwing an instance of 'base::gdk_exception_t'
`

**Comment by izzylaif** [comment]
The version that works is [https://apprepo.de/appimage/download/anydesk](url) by Alex Woroshilov.
It's a much larger package, and if I put anydesk from bin of your package to that one (i.e updating the executable from 5.x to 6.x) it launches.

**Comment by ivan-hc** [comment]
I don't know how AppRepo creates its AppImages, the fact him does not provides source code make me aware not to trust on its creations. However I will try to test again to fix the issue on Arch-based systems. On Debian and derivatives my Appimage should work well.

Stay tuned.

**Comment by izzylaif** [comment]
He does though [https://github.com/area-of-dev/AnyDesk.AppImage/commit/919454be84a81045bc28217174e1f9820f2c75fe](url)

**Comment by ivan-hc** [comment]
I talk about its MAKE file in the main path of the repository: what is  that "Apprepo.AppImage" him uses to build its AppImages? I have already seen its internals and I don't know what it really does while patching the Appimages. I have tested them and all work great... but this method, with the sizes of its AppImages does not convinces me. This is why I build them by myself.

**Comment by ivan-hc** [comment]
oh my... I forgot to add "/lib" in LD_LIBRARY_PATH! Maybe the issue is there! This is an old template of the early days.

Now I'll start a new release, wait 10 minutes.

**Comment by ivan-hc** [comment]
If this does not works, try this other solution


[anydesk-bin-junest.sh.zip](https://github.com/ivan-hc/Anydesk-appimage/files/12135724/anydesk-bin-junest.sh.zip)

Download this script, run it into a temporary directory of your choice, this will generate an AppImage of Anydesk from AUR (Arch Linux).

In case you have problems when th script enables your local mirrors for pacman, comment (add # at the start of) the lines from 30 to 32 and try again.

Then let me know it it works for you.

**Comment by izzylaif** [comment]
the releases build does not work
the script-produced appimage does work.

**Comment by ivan-hc** [comment]
I need a favor from you: you should run Anydesk from ***./anydesk.AppDir/AppRun***, remove unnecessary files from ***./anydesk.AppDir/.junest/*** (and list what you removed) then try to start the app again by running the ***AppRun***.

This operation serves to lighten the size of the final package (it is now 266MB, but could be even smaller).

**Comment by ivan-hc** [comment]
for example, add this at line 1258 and run the script again (results a 127MB AppImage)

```
# ADDITIONAL REMOVALS
rm -R -f ./$APP.AppDir/.junest/usr/lib/audit
rm -R -f ./$APP.AppDir/.junest/usr/lib/avahi
rm -R -f ./$APP.AppDir/.junest/usr/lib/awk
rm -R -f ./$APP.AppDir/.junest/usr/lib/bash
rm -R -f ./$APP.AppDir/.junest/usr/lib/bellagio
rm -R -f ./$APP.AppDir/.junest/usr/lib/cmake
rm -R -f ./$APP.AppDir/.junest/usr/lib/d3d
rm -R -f ./$APP.AppDir/.junest/usr/lib/dri
rm -R -f ./$APP.AppDir/.junest/usr/lib/libgo.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libLLVM*
rm -R -f ./$APP.AppDir/.junest/usr/lib/perl*
rm -R -f ./$APP.AppDir/.junest/usr/lib/python*
rm -R -f ./$APP.AppDir/.junest/usr/lib/systemd
rm -R -f ./$APP.AppDir/.junest/usr/lib/udev
rm -R -f ./$APP.AppDir/.junest/usr/share/aclocal
rm -R -f ./$APP.AppDir/.junest/usr/share/audit
rm -R -f ./$APP.AppDir/.junest/usr/share/awk
rm -R -f ./$APP.AppDir/.junest/usr/share/emacs
rm -R -f ./$APP.AppDir/.junest/usr/share/gir-*
rm -R -f ./$APP.AppDir/.junest/usr/share/hwdata
rm -R -f ./$APP.AppDir/.junest/usr/share/perl*
rm -R -f ./$APP.AppDir/.junest/usr/share/ss
rm -R -f ./$APP.AppDir/.junest/usr/share/systemd
rm -R -f ./$APP.AppDir/.junest/usr/share/tabset
rm -R -f ./$APP.AppDir/.junest/usr/share/terminfo
rm -R -f ./$APP.AppDir/.junest/usr/share/vala
rm -R -f ./$APP.AppDir/.junest/usr/share/wayland
rm -R -f ./$APP.AppDir/.junest/usr/share/X11
rm -R -f ./$APP.AppDir/.junest/usr/share/xml
rm -R -f ./$APP.AppDir/.junest/usr/share/xtables
rm -R -f ./$APP.AppDir/.junest/usr/share/zoneinfo
rm -R -f ./$APP.AppDir/.junest/usr/share/zoneinfo-leaps
rm -R -f ./$APP.AppDir/.junest/usr/share/zoneinfo-posix
rm -R -f ./$APP.AppDir/.junest/usr/share/zsh
```

**Comment by ivan-hc** [comment]
Update, try to add this instead (final sizes 91MB)

```
# ADDITIONAL REMOVALS
rm -R -f ./$APP.AppDir/.junest/usr/lib/audit
rm -R -f ./$APP.AppDir/.junest/usr/lib/avahi
rm -R -f ./$APP.AppDir/.junest/usr/lib/awk
rm -R -f ./$APP.AppDir/.junest/usr/lib/bash
rm -R -f ./$APP.AppDir/.junest/usr/lib/bellagio
rm -R -f ./$APP.AppDir/.junest/usr/lib/cmake
rm -R -f ./$APP.AppDir/.junest/usr/lib/d3d
rm -R -f ./$APP.AppDir/.junest/usr/lib/dri
rm -R -f ./$APP.AppDir/.junest/usr/lib/gconv
rm -R -f ./$APP.AppDir/.junest/usr/lib/libasan.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libgo.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libgphobos.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libicudata.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libicui18n.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libicuio.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libicutest.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libicutu.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libicuuc.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libLLVM*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libOSMesa.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libpython*
rm -R -f ./$APP.AppDir/.junest/usr/lib/perl*
rm -R -f ./$APP.AppDir/.junest/usr/lib/python*
rm -R -f ./$APP.AppDir/.junest/usr/lib/sysctl.d
rm -R -f ./$APP.AppDir/.junest/usr/lib/systemd
rm -R -f ./$APP.AppDir/.junest/usr/lib/sysusers.d
rm -R -f ./$APP.AppDir/.junest/usr/lib/tmpfiles.d
rm -R -f ./$APP.AppDir/.junest/usr/lib/udev
rm -R -f ./$APP.AppDir/.junest/usr/lib/utempter
rm -R -f ./$APP.AppDir/.junest/usr/lib/xtables
rm -R -f ./$APP.AppDir/.junest/usr/share/aclocal
rm -R -f ./$APP.AppDir/.junest/usr/share/audit
rm -R -f ./$APP.AppDir/.junest/usr/share/awk
rm -R -f ./$APP.AppDir/.junest/usr/share/emacs
rm -R -f ./$APP.AppDir/.junest/usr/share/gir-*
rm -R -f ./$APP.AppDir/.junest/usr/share/hwdata
rm -R -f ./$APP.AppDir/.junest/usr/share/perl*
rm -R -f ./$APP.AppDir/.junest/usr/share/ss
rm -R -f ./$APP.AppDir/.junest/usr/share/systemd
rm -R -f ./$APP.AppDir/.junest/usr/share/tabset
rm -R -f ./$APP.AppDir/.junest/usr/share/terminfo
rm -R -f ./$APP.AppDir/.junest/usr/share/vala
rm -R -f ./$APP.AppDir/.junest/usr/share/wayland
rm -R -f ./$APP.AppDir/.junest/usr/share/X11
rm -R -f ./$APP.AppDir/.junest/usr/share/xml
rm -R -f ./$APP.AppDir/.junest/usr/share/xtables
rm -R -f ./$APP.AppDir/.junest/usr/share/zoneinfo*
rm -R -f ./$APP.AppDir/.junest/usr/share/zsh
```

**Comment by ivan-hc** [comment]
UPDATE 2: with this the AppImage is 66MB

```
# ADDITIONAL REMOVALS
rm -R -f ./$APP.AppDir/.junest/usr/lib/audit
rm -R -f ./$APP.AppDir/.junest/usr/lib/avahi
rm -R -f ./$APP.AppDir/.junest/usr/lib/awk
rm -R -f ./$APP.AppDir/.junest/usr/lib/bash
rm -R -f ./$APP.AppDir/.junest/usr/lib/bellagio
rm -R -f ./$APP.AppDir/.junest/usr/lib/cmake
rm -R -f ./$APP.AppDir/.junest/usr/lib/d3d
rm -R -f ./$APP.AppDir/.junest/usr/lib/dri
rm -R -f ./$APP.AppDir/.junest/usr/lib/gconv
rm -R -f ./$APP.AppDir/.junest/usr/lib/libasan.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libcrypt*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libdb-*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libdb.*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libdb_*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libgdruntime.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libgfortran.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libgo.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libgphobos.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libgprofng.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libicudata.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libicui18n.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libicuio.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libicutest.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libicutu.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libicuuc.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libLLVM*
rm -R -f ./$APP.AppDir/.junest/usr/lib/liblsan.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libOSMesa.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libpython*
rm -R -f ./$APP.AppDir/.junest/usr/lib/librsvg-2.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libtsan.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libubsan.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/libxatracker.so*
rm -R -f ./$APP.AppDir/.junest/usr/lib/perl*
rm -R -f ./$APP.AppDir/.junest/usr/lib/python*
rm -R -f ./$APP.AppDir/.junest/usr/lib/sysctl.d
rm -R -f ./$APP.AppDir/.junest/usr/lib/systemd
rm -R -f ./$APP.AppDir/.junest/usr/lib/sysusers.d
rm -R -f ./$APP.AppDir/.junest/usr/lib/tmpfiles.d
rm -R -f ./$APP.AppDir/.junest/usr/lib/udev
rm -R -f ./$APP.AppDir/.junest/usr/lib/utempter
rm -R -f ./$APP.AppDir/.junest/usr/lib/xtables
rm -R -f ./$APP.AppDir/.junest/usr/share/aclocal
rm -R -f ./$APP.AppDir/.junest/usr/share/audit
rm -R -f ./$APP.AppDir/.junest/usr/share/awk
rm -R -f ./$APP.AppDir/.junest/usr/share/doc
rm -R -f ./$APP.AppDir/.junest/usr/share/drirc.d
rm -R -f ./$APP.AppDir/.junest/usr/share/emacs
rm -R -f ./$APP.AppDir/.junest/usr/share/fish
rm -R -f ./$APP.AppDir/.junest/usr/share/gir-*
rm -R -f ./$APP.AppDir/.junest/usr/share/hwdata
rm -R -f ./$APP.AppDir/.junest/usr/share/i18n
rm -R -f ./$APP.AppDir/.junest/usr/share/java
rm -R -f ./$APP.AppDir/.junest/usr/share/perl*
rm -R -f ./$APP.AppDir/.junest/usr/share/ss
rm -R -f ./$APP.AppDir/.junest/usr/share/systemd
rm -R -f ./$APP.AppDir/.junest/usr/share/tabset
rm -R -f ./$APP.AppDir/.junest/usr/share/terminfo
rm -R -f ./$APP.AppDir/.junest/usr/share/vala
rm -R -f ./$APP.AppDir/.junest/usr/share/wayland
rm -R -f ./$APP.AppDir/.junest/usr/share/X11
rm -R -f ./$APP.AppDir/.junest/usr/share/xml
rm -R -f ./$APP.AppDir/.junest/usr/share/xtables
rm -R -f ./$APP.AppDir/.junest/usr/share/zoneinfo*
rm -R -f ./$APP.AppDir/.junest/usr/share/zsh
```
Let me know if it works.

**Comment by ivan-hc** [comment]
[anydesk-bin-junest.sh.zip](https://github.com/ivan-hc/Anydesk-appimage/files/12136739/anydesk-bin-junest.sh.zip)

**Comment by izzylaif** [comment]
both 121 and 64mb versions work.

**Comment by ivan-hc** [comment]
Great https://github.com/ivan-hc/Anydesk-appimage/commit/5cbcb62824cbfaaabfd7a92f4e795e5a873d99cc
