### ISSUE TITLE
AppImageLauncher error: appimage_shall_not_be_integrated()

### ISSUE THREAD

**Issue by kamilkobak** [ivan-hc/Anydesk-appimage#4]
I have this error on Ubuntu 24.04:
`# ./Anydesk-6.3.3-x86_64_e10c4d94a06397eec61633ae06bc3e3c.AppImage 
AppImageLauncher error: appimage_shall_not_be_integrated() failed (returned -1)
AppImageLauncher error: appimage_is_terminal_app() failed (returned -1)
execv error: No such file or directory
`

**Comment by ivan-hc** [comment]
It is a known issue. Please read this https://github.com/ivan-hc/AM/releases/tag/8.3.1

**Comment by ivan-hc** [comment]
SPOILER: remove appimagelauncher, reboot and retry
